# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - node:6

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
